name: flutter_system_ringtones
description: An Android & iOS (WIP) plugin to retrieve a list of system ringtones using native API's
version: 0.0.3
homepage: https://pub.dev/packages/flutter_system_ringtones
repository: https://github.com/imedboumalek/flutter_system_ringtones

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.pavlok.flutter_system_ringtones
        pluginClass: FlutterSystemRingtonesPlugin
      ios:
        pluginClass: FlutterSystemRingtonesPlugin
